In [2]:
import pyupbit
import pandas as pd

In [7]:
Bit_df = pyupbit.get_ohlcv("KRW-BTC",count = 2200, period=1,interval= "minute240", to="20241203")
Ether_df = pyupbit.get_ohlcv("KRW-ETH",count = 2200, period=1,interval= "minute240", to="20241203")
tether_df = pyupbit.get_ohlcv("KRW-USDT",count = 2200, period=1,interval= "minute240", to="20241203")
Doge_df = pyupbit.get_ohlcv("KRW-DOGE",count = 2200, period=1,interval= "minute240", to="20241203")
Sand_df = pyupbit.get_ohlcv("KRW-SAND",count = 2200, period=1,interval= "minute240", to="20241203")
XRP_df = pyupbit.get_ohlcv("KRW-XRP",count = 2200, period=1,interval= "minute240", to="20241203")
Solana_df = pyupbit.get_ohlcv("KRW-SOL",count = 2200, period=1,interval= "minute240", to="20241203")
Shib_df = pyupbit.get_ohlcv("KRW-SHIB",count = 2200, period=1,interval= "minute240", to="20241203")

bit_high = Bit_df['high']
dog_high = Doge_df['high']
eth_high = Ether_df['high']
sol_high = Solana_df['high']
sand_high = Sand_df ['high']
shib_high = Shib_df['high']
XRP_high = XRP_df['high']
tether_high = tether_df['high']

coin_list = [Bit_df,Ether_df,tether_df,Doge_df,Sand_df,XRP_df,Solana_df,Shib_df]
coin_list_name = ['Bit','Ether','tether','Doge','Sand','XRP','Solana','Shib']
coin_list_high = []
for i in coin_list:
    coin_list_high.append(i['high'])

df_coin_high = pd.concat(coin_list_high,axis=1,keys=coin_list_name)

In [11]:
Bit_low = Bit_df['low']
dog_low = Doge_df['low']
eth_low = Ether_df['low']
sol_low = Solana_df['low']
sand_low = Sand_df ['low']
shib_low = Shib_df['low']
XRP_low = XRP_df['low']
tether_low = tether_df['low']

coin_list = [Bit_df,Ether_df,tether_df,Doge_df,Sand_df,XRP_df,Solana_df,Shib_df]
coin_list_name = ['Bit','Ether','tether','Doge','Sand','XRP','Solana','Shib']
coin_list_low = []
for i in coin_list:
    coin_list_low.append(i['low'])

df_coin_low = pd.concat(coin_list_low,axis=1,keys=coin_list_name)

In [12]:
Bit_volume = Bit_df['volume']
dog_volume = Doge_df['volume']
eth_volume = Ether_df['volume']
sol_volume = Solana_df['volume']
sand_volume = Sand_df ['volume']
shib_volume = Shib_df['volume']
XRP_volume = XRP_df['volume']
tether_volume = tether_df['volume']

coin_list = [Bit_df,Ether_df,tether_df,Doge_df,Sand_df,XRP_df,Solana_df,Shib_df]
coin_list_name = ['Bit','Ether','tether','Doge','Sand','XRP','Solana','Shib']
coin_list_volume = []
for i in coin_list:
    coin_list_volume.append(i['volume'])

df_coin_volume = pd.concat(coin_list_volume,axis=1,keys=coin_list_name)

In [ ]:
# df_coin_high
# df_coin_low
# df_coin_volume

In [16]:
Bit_df_day = pyupbit.get_ohlcv("KRW-BTC",count = 51, period=1,interval= "minute60", to="20241205")

In [17]:
Bit_df_day.head()

,open,high,low,close,volume,value
2024-12-03 06:00:00,133611000.0,133805000.0,133070000.0,133303000.0,127.507839,1.700612e+10
2024-12-03 07:00:00,133303000.0,133500000.0,133093000.0,133095000.0,139.520695,1.859185e+10
2024-12-03 08:00:00,133095000.0,133600000.0,133000000.0,133535000.0,166.623268,2.219644e+10
2024-12-03 09:00:00,133523000.0,134250000.0,133357000.0,133970000.0,281.766419,3.771861e+10
2024-12-03 10:00:00,133970000.0,134000000.0,133371000.0,133753000.0,177.488796,2.371933e+10

In [18]:
Bit_df_day = pyupbit.get_ohlcv("KRW-BTC",count = 51, period=1,interval= "minute60", to="20241205")
Ether_df_day = pyupbit.get_ohlcv("KRW-ETH",count = 51, period=1,interval= "minute60", to="20241205")
tether_df_day = pyupbit.get_ohlcv("KRW-USDT",count = 51, period=1,interval= "minute60", to="20241205")
Doge_df_day = pyupbit.get_ohlcv("KRW-DOGE",count = 51, period=1,interval= "minute60", to="20241205")
Sand_df_day = pyupbit.get_ohlcv("KRW-SAND",count = 51, period=1,interval= "minute60", to="20241205")
XRP_df_day = pyupbit.get_ohlcv("KRW-XRP",count = 51, period=1,interval= "minute60", to="20241205")
Solana_df_day = pyupbit.get_ohlcv("KRW-SOL",count = 51, period=1,interval= "minute60", to="20241205")
Shib_df_day = pyupbit.get_ohlcv("KRW-SHIB",count = 51, period=1,interval= "minute60", to="20241205")

bit_high_day = Bit_df_day['high']
dog_high_day = Doge_df_day['high']
eth_high_day = Ether_df_day['high']
sol_high_day = Solana_df_day['high']
sand_high_day = Sand_df_day ['high']
shib_high_day = Shib_df_day['high']
XRP_high_day = XRP_df_day['high']
tether_high_day = tether_df_day['high']

coin_list = [Bit_df_day,Ether_df_day,tether_df_day,Doge_df_day,Sand_df_day,XRP_df_day,Solana_df_day,Shib_df_day]
coin_list_name = ['Bit','Ether','tether','Doge','Sand','XRP','Solana','Shib']
coin_list_high = []
for i in coin_list:
    coin_list_high.append(i['high'])

df_coin_high_day = pd.concat(coin_list_high,axis=1,keys=coin_list_name)

In [20]:
bit_low_day = Bit_df_day['low']
dog_low_day = Doge_df_day['low']
eth_low_day = Ether_df_day['low']
sol_low_day = Solana_df_day['low']
sand_low_day = Sand_df_day ['low']
shib_low_day = Shib_df_day['low']
XRP_low_day = XRP_df_day['low']
tether_low_day = tether_df_day['low']

coin_list = [Bit_df_day,Ether_df_day,tether_df_day,Doge_df_day,Sand_df_day,XRP_df_day,Solana_df_day,Shib_df_day]
coin_list_name = ['Bit','Ether','tether','Doge','Sand','XRP','Solana','Shib']
coin_list_low = []
for i in coin_list:
    coin_list_low.append(i['low'])

df_coin_low_day = pd.concat(coin_list_low,axis=1,keys=coin_list_name)

In [23]:
bit_volume_day = Bit_df_day['volume']
dog_volume_day = Doge_df_day['volume']
eth_volume_day = Ether_df_day['volume']
sol_volume_day = Solana_df_day['volume']
sand_volume_day = Sand_df_day ['volume']
shib_volume_day = Shib_df_day['volume']
XRP_volume_day = XRP_df_day['volume']
tether_volume_day = tether_df_day['volume']

coin_list = [Bit_df_day,Ether_df_day,tether_df_day,Doge_df_day,Sand_df_day,XRP_df_day,Solana_df_day,Shib_df_day]
coin_list_name = ['Bit','Ether','tether','Doge','Sand','XRP','Solana','Shib']
coin_list_volume = []
for i in coin_list:
    coin_list_volume.append(i['volume'])

df_coin_volume_day = pd.concat(coin_list_volume,axis=1,keys=coin_list_name)

In [29]:
df_coin_high

,Bit,Ether,tether,Doge,Sand,XRP,Solana,Shib
2023-12-02 13:00:00,51917000.0,2812000.0,NaN,113.0,559.0,822.0,83610.0,0.01130
2023-12-02 17:00:00,51780000.0,2810000.0,NaN,113.0,564.0,821.0,83200.0,0.01130
2023-12-02 21:00:00,51850000.0,2813000.0,NaN,113.0,565.0,821.0,83370.0,0.01130
2023-12-03 01:00:00,52417000.0,2892000.0,NaN,115.0,572.0,828.0,83670.0,0.01140
2023-12-03 05:00:00,52833000.0,2894000.0,NaN,116.0,576.0,828.0,85240.0,0.01140
...,...,...,...,...,...,...,...,...
2024-12-02 13:00:00,134846000.0,5158000.0,1399.0,621.7,910.0,3447.0,321300.0,0.04238
2024-12-02 17:00:00,134125000.0,5121000.0,1407.0,600.7,902.0,3419.0,319600.0,0.04213
2024-12-02 21:00:00,134990000.0,5135000.0,1410.0,614.2,903.0,3820.0,319700.0,0.04190
2024-12-03 01:00:00,135000000.0,5115000.0,1405.0,608.9,906.0,3957.0,319450.0,0.04154
2024-12-03 05:00:00,134250000.0,5089000.0,1401.0,596.0,1020.0,3895.0,316200.0,0.04181

In [31]:
df_coin_high = pd.concat([df_coin_high,df_coin_high_day])

In [34]:
df_coin_low = pd.concat([df_coin_low,df_coin_low_day])

In [35]:
df_coin_volume = pd.concat([df_coin_volume,df_coin_volume_day])

In [36]:
import pandas as pd

In [40]:
df_coin_high.to_csv('coin_high.csv',index=True)

In [41]:
df_coin_low.to_csv('coin_low.csv',index=True)

In [42]:
df_coin_volume.to_csv('coin_volume.csv',index=True)